/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/ui/AppButton.vue')['default']
    AppHeader: typeof import('./src/components/ui/AppHeader.vue')['default']
    AppInput: typeof import('./src/components/ui/AppInput.vue')['default']
    AppLink: typeof import('./src/components/ui/AppLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    ULink: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/overrides/vue-router/Link.vue')['default']
  }
}
